### ISSUE TITLE
TapDance + One-Shots

### ISSUE THREAD

**Issue by algernon** [algernon/Akela#41]
What happens when one activates a one-shot layer, then taps a tap-dance key there?

---

The behaviour I'd expect, is that the layer stays active until an action triggers. This is not currently the case, so, both of these features should be improved to work together, as one would expect.

Thanks to @eltang for bringing this corner case to my attention.

**Comment by eltang** [comment]
Another issue I've had does not have such a clear answer, and that is whether or not clicking and scrolling with a mouse should influence active one-shot modifiers just like pressing keys on the keyboard does. They should, but making that happen will be slightly difficult. That's why I've decided to leave one-shot modifiers out of my firmware altogether for now.

**Comment by algernon** [comment]
That's also doable, but requires coordination from the mouse - or the OS. Doable if the keyboard also has a "serial" listener. But I wouldn't worry about it, to be honest: all these fancy keys are for the keyboard only, their interaction with other devices is out of scope for a keyboard firmware, in my opinion.
